apiVersion: apps/v1
kind: Deployment
metadata:
  name: electricitypricing
  namespace: "proj-gr4"
  labels:
    app: electricitypricing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electricitypricing
  template:
    metadata:
      labels:
        app: electricitypricing
    spec:
      containers:
      - name: electricitypricing
        image: 201608930/electricitypricing:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata: 
  name: electricitypricing
  namespace: "proj-gr4"
  labels:
    app: electricitypricing
spec:
  selector:
    app: electricitypricing
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
    
      
      
